# Generated by Django 4.0.4 on 2022-04-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=100)),
                ('malumot', models.TextField()),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='post_image')),
                ('video', models.FileField(blank=True, null=True, upload_to='post_video')),
                ('kurishlar', models.IntegerField(default=1)),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
